# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(724, 363)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Login.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        Login.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Login)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(131, 80, 341, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.password1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password1.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password1.setObjectName("password1")
        self.verticalLayout.addWidget(self.password1)
        self.password2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password2.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password2.setObjectName("password2")
        self.verticalLayout.addWidget(self.password2)
        self.cancel = QtWidgets.QPushButton(Login)
        self.cancel.setGeometry(QtCore.QRect(550, 310, 111, 41))
        self.cancel.setObjectName("cancel")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 261, 41))
        self.label_3.setObjectName("label_3")
        self.register_2 = QtWidgets.QPushButton(Login)
        self.register_2.setGeometry(QtCore.QRect(410, 310, 111, 41))
        self.register_2.setObjectName("register_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Login)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 80, 101, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.employer = QtWidgets.QRadioButton(Login)
        self.employer.setGeometry(QtCore.QRect(490, 100, 211, 31))
        self.employer.setObjectName("employer")
        self.seeker = QtWidgets.QRadioButton(Login)
        self.seeker.setGeometry(QtCore.QRect(490, 170, 231, 31))
        self.seeker.setObjectName("seeker")
        self.errors = QtWidgets.QLineEdit(Login)
        self.errors.setGeometry(QtCore.QRect(40, 320, 339, 30))
        self.errors.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.errors.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.errors.setObjectName("errors")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.cancel.setText(_translate("Login", "Cancel"))
        self.label_3.setText(_translate("Login", "Бюро працевлаштування"))
        self.register_2.setText(_translate("Login", "Register"))
        self.label.setText(_translate("Login", "Username"))
        self.label_2.setText(_translate("Login", "Password"))
        self.label_4.setText(_translate("Login", "Password"))
        self.employer.setText(_translate("Login", "Register as еmployer"))
        self.seeker.setText(_translate("Login", "Register as Job seeker"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
